---
title: "Session 7 & 8"
author: "Tolga Akturk"
date: '2022-03-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(skimr)

#Assessement 1 C

#Q19
#Explained mutate then cut number (variable name) then, n=3, then similar process to case when

#Q20
#ggplot in this case, discrete variable, include facets, coordinates and themes

#Q21 second variable
#mutate, transfat / total fat x 100 

#Q22
#similar to Q20 however calories type will be discrete, trans  fat is continuos so different geom I need to apply

#Q23
#grouping then summarise 

#Q24
#compare restaurants on total fat so discrete and continous. Which geom will I use? Simple one no need for facets etc. 

```

```{r}

#Assessment 2

#Homework - have a look at it and we will cover Thursday

```

``` {r}

coffee_ratings<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')

skim(coffee_ratings)
```

```{r}

#working on forcats on Tidyverse

#option 1 to convert on factors

coffee_ratings<-coffee_ratings%>%
  mutate(
    species=as_factor(species), 
    country_of_origin=as_factor(country_of_origin)
  )

```

```{r}

#option 2

coffee_ratings$owner<-as_factor(coffee_ratings$owner)

```




